# __Z_score normalization__
---
- 최초작성일: 20-05-24

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import array

%matplotlib inline

In [4]:
def z_score_normalize(lst):
    normalized = []
    for value in lst:
        normalized_num = (value - np.mean(lst)) / np.std(lst)
        normalized.append(normalized_num)
    return normalized

In [3]:
df = pd.read_csv("../LSTM2/data/lnch_long_rel_0523_menu_fillna.csv")

In [4]:
df.columns

Index(['timestamp', 'target_value', 'item_id', 'rainfall', 'rain_prob',
       'temperature', 'abnormal', 'holiday', 'before_holiday', 'after_holiday',
       'closed', 'mon', 'tue', 'wed', 'thur', 'fri', 'sat', 'sun',
       'dayofweek_median', 'dayofweek_mean', 'day_cos', 'day_sin', 'menu',
       'menu_nouns', 'menu_origin', 'menu_nouns2', 'scaled_target', 'cnt',
       'weekday', 'same_menu'],
      dtype='object')

In [6]:
df['rainfall'] = z_score_normalize(df['rainfall'])

In [9]:
df['rain_prob'] = z_score_normalize(df['rain_prob'])

In [10]:
df['temperature'] = z_score_normalize(df['temperature'])

In [11]:
df['dayofweek_median'] = z_score_normalize(df['dayofweek_median'])

In [12]:
df['same_menu'] = z_score_normalize(df['same_menu'])

In [13]:
df.to_csv("../LSTM2/data/lnch_long_rel_0524_zscore.csv", index=False)

In [2]:
df = pd.read_csv("../LSTM2/data/lnch_long_rel_0524_zscore.csv")

In [5]:
df['cnt'] = z_score_normalize(df['cnt'])

In [18]:
df['dayofweek_median'] =

0      -2.982234
1       1.894511
2       1.577212
3       1.308198
4       1.515132
          ...
1181   -0.333479
1182   -2.982234
1183   -2.982234
1184    1.894511
1185    1.577212
Name: dayofweek_median, Length: 1186, dtype: float64

In [7]:
df.to_csv("../LSTM2/data/lnch_long_rel_0526_zscore.csv", index= False)

In [8]:
df

,timestamp,target_value,item_id,rainfall,rain_prob,temperature,abnormal,holiday,before_holiday,after_holiday,...,day_cos,day_sin,menu,menu_nouns,menu_origin,menu_nouns2,scaled_target,cnt,weekday,same_menu
0,2017-01-01,0,중식_소계,-0.254093,0.072296,-0.674727,0,1,0,0,...,1.000000,-2.450000e-16,NaN,NaN,NaN,NaN,NaN,-1.343939,6,-1.314733
1,2017-01-02,360,중식_소계,-0.228544,-0.877770,-0.742450,0,0,0,1,...,0.623490,7.818315e-01,"모듬생선구이<가자미, 꽁치>",모듬생선구이 가자미 꽁치,NaN,모듬생선구이,1.621053,-1.343939,0,1.011391
2,2017-01-03,376,중식_소계,-0.254093,-0.877770,-0.926267,0,0,0,0,...,-0.222521,9.749279e-01,돈육단호박찜 (돈육: 미국산),돈육단호박찜,돼지고기,돈육단호박찜,1.789474,0.933373,1,0.905038
3,2017-01-04,396,중식_소계,-0.254093,-0.877770,-0.848870,0,0,0,0,...,-0.900969,4.338837e-01,"기츠동 (돈육: 국내산, 배추:국내, 고추분: 중국)",기츠동,돼지고기 배추,가츠동,2.000000,0.939511,2,1.166187
4,2017-01-05,367,중식_소계,-0.254093,0.072296,-0.558632,0,0,0,0,...,-0.900969,-4.338837e-01,"쑥갓동태알탕 (동태: 러시아, 대구고니: 미국)",쑥갓동태알탕,동태 대구고니 미국,알탕,1.694737,0.835160,3,0.543071
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1181,2020-03-27,148,중식_소계,-0.083764,-0.877770,-0.355465,0,0,0,0,...,-0.222521,-9.749279e-01,탕수육&소스\n(돼지고기:국내산),탕수육 소스\n,돼지고기,탕수육,1.000000,NaN,4,-0.074273
1182,2020-03-28,0,중식_소계,-0.254093,-0.877770,-0.548957,0,0,0,0,...,0.623490,-7.818315e-01,NaN,NaN,NaN,NaN,NaN,NaN,5,-1.314733
1183,2020-03-29,0,중식_소계,-0.254093,0.072296,-0.278068,0,0,0,0,...,1.000000,-2.450000e-16,NaN,NaN,NaN,NaN,NaN,NaN,6,-1.314733
1184,2020-03-30,350,중식_소계,-0.254093,0.072296,-0.316766,0,0,0,0,...,0.623490,7.818315e-01,닭갈비(닭갈비:국내산),닭갈비,닭갈비,닭갈비,2.000000,NaN,0,0.918186
1185,2020-03-31,302,중식_소계,-0.254093,0.072296,-0.007178,0,0,0,0,...,-0.222521,9.749279e-01,오므라이스&케찹,오므라이스 케찹,NaN,오므라이스,1.000000,NaN,1,0.745863

In [13]:
df.drop('menu_nouns', axis = 1)
df.to_csv("../LSTM2/data/lnch_long_rel_0526.csv", index= False)